name: Fetch runtime assets (no commit)

on:
  workflow_dispatch:
    inputs:
      asset_url:
        description: "URL архива с ассетами (zip/7z)"
        required: true
      target_dir:
        description: "Куда распаковать в раннере"
        required: false
        default: "assets_1/art"

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 1 }

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y p7zip-full unzip

      - name: Download archive
        run: |
          mkdir -p _dl
          set -e
          if curl -L "${{ github.event.inputs.asset_url }}" -o _dl/assets.7z; then
            echo "Got .7z"
          elif curl -L "${{ github.event.inputs.asset_url }}" -o _dl/assets.zip; then
            echo "Got .zip"
          else
            echo "Failed to download archive" && exit 1
          fi

      - name: Extract
        run: |
          mkdir -p "${{ github.event.inputs.target_dir }}"
          if [ -f _dl/assets.7z ]; then
            7z x _dl/assets.7z -o"${{ github.event.inputs.target_dir }}" -y
          else
            unzip -q _dl/assets.zip -d "${{ github.event.inputs.target_dir }}"
          fi
          echo "Extracted to ${{ github.event.inputs.target_dir }}"
